/* Auto-generated by the admin "Export for publishing" — 2026-06-20.
   Drop this file at src/published.js and the images/ files into images/,
   regenerate standalone.html (or rebuild), then deploy. Visitors see this. */
window.__PUBLISHED__ = {
  "roleProjects": {
    "product": [
      {
        "id": "lean-design-system",
        "title": "Creating a lean design system",
        "project": "YesOnline E-Learning System",
        "year": "2023–2025",
        "duo": [
          "#0F172A",
          "#4C6B8A"
        ],
        "tags": [
          "Design system",
          "UI Design",
          "Teamwork"
        ],
        "summary": "I translated user insights and business goals into a consistent, data-informed product experience.",
        "blog": {
          "intro": "In this project, I worked as a UX/UI Designer, focusing on aligning design consistency with broader business goals. Through an end-to-end design process, including user interviews, usability testing, and A/B testing, I transformed research findings into practical design decisions. This approach helped ensure that the final experience was not only visually cohesive, but also grounded in real user needs and measurable product value.\n\nI restructured the original design system, streamlining convoluted settings and establishing clear definitions. I also worked closely with the engineering team to align on implementation and compliance.",
          "sections": [
            {
              "h": "The Challenges: Former System",
              "p": "The previous design system relied on three distinct sets of assets for different devices. This fragmented approach caused confusion, as even the color specifications became inconsistent between the mobile and web versions, making it difficult to maintain brand unity."
            },
            {
              "type": "image",
              "src": "product-creating-a-lean-design-system-2.jpg",
              "caption": ""
            },
            {
              "h": "Confusion for Developers",
              "p": "While attempting to accelerate the development process, we discovered that the fragmented button components caused significant visual inconsistencies in the frontend. I had to invest considerable time auditing existing styles while ensuring new designs remained backward-compatible — all while managing the high-pressure timeline set by leadership and engineering."
            },
            {
              "h": "Buttons, buttons, and more buttons",
              "p": "Following a period of cross-functional alignment, I successfully overhauled the system into a leaner version. I kicked off this initiative by standardizing the button library, ensuring that the most frequently used elements were the first to benefit from the new, simplified architecture."
            },
            {
              "type": "image",
              "src": "product-creating-a-lean-design-system-5.jpg",
              "caption": ""
            },
            {
              "h": "Next step: Keeping Design-to-Code Alignment Seamless",
              "p": "After revamping the design system, the development velocity has significantly increased, allowing engineers to build interfaces more efficiently. On the design side, this standardized framework enables me to produce high-fidelity prototypes much faster, ensuring that we can iterate and validate ideas with minimal overhead.\n\nTo ensure the system remains maintainable and scalable, we introduced Storybook as our single source of truth. This prevents the creation of \"redundant variants\" — such as \"twin buttons\" with slight, unauthorized differences. By implementing Storybook, we've achieved a seamless alignment between design and code, allowing both teams to develop and test components in isolation while maintaining total visual integrity."
            }
          ],
          "quote": null
        },
        "cover": "product-creating-a-lean-design-system.jpg"
      },
      {
        "id": "why-design-system-matters",
        "title": "Why Does a Design System Matter?",
        "year": "2024–2025",
        "duo": [
          "#1E293B",
          "#6B7F6B"
        ],
        "tags": [
          "Design System",
          "UI Design",
          "System Thinking"
        ],
        "summary": "I built a scalable design system for a 0-to-1 B2B CRM, defining core principles and reusable components to support complex workflows, design consistency, and faster product development.",
        "blog": {
          "intro": "In this 0-to-1 B2B CRM project, the design system became the foundation for scaling a complex internal product from the ground up. Instead of treating UI design as screen production, I focused on defining the product’s visual and interaction DNA through clear design principles, reusable components, and a structured Figma library. By applying Atomic Design methodology, I helped the team move from page-based design to a component-based ecosystem that supported data readability, workflow efficiency, error prevention, and faster feature delivery.",
          "sections": [
            {
              "h": "Scaling a B2B Ecosystem from the Ground Up",
              "p": "In a 0-1 project, the UI designer's role isn't just to \"draw screens\" — it's to define the DNA of the product. To ensure the new CRM could handle the weight of complex registration workflows while staying agile, I established a set of Core Design Principles to guide every pixel."
            },
            {
              "h": "Establishing Design Principles: Our North Star",
              "p": "Before opening Figma, I defined three pillars to ensure the system remained cohesive as it grew from zero to one:\n\n• Clarity Over Decoration: In a high-intensity work environment, every element must serve a purpose. We prioritize data readability over trendy aesthetics.\n• Consistency Breeds Efficiency: Predictable patterns reduce the learning curve. If a \"Submit\" button looks a certain way in Registration, it must look the same in Reporting.\n• Forgiving Design: Human error is inevitable in manual data entry. Our system must provide clear feedback and \"undo\" paths to prevent costly mistakes."
            },
            {
              "type": "image",
              "src": "product-why-does-a-design-system-matter-3.jpg",
              "caption": ""
            },
            {
              "type": "image",
              "src": "product-why-does-a-design-system-matter-4.jpg",
              "caption": ""
            },
            {
              "type": "image",
              "src": "product-why-does-a-design-system-matter-5.jpg",
              "caption": ""
            },
            {
              "h": "The Atomic Foundation: Building for Scale",
              "p": "To hit our 10% efficiency goal, I adopted the Atomic Design methodology. I moved away from \"page-based\" design toward a \"component-based\" ecosystem.\n\n• The Atoms: I standardized typography scales, a B2B-optimized color palette (prioritizing high contrast and reduced eye strain), and a strict 8px grid system.\n• The Library: By building a centralized Figma component library, we ensured that developers could reuse code, drastically reducing the \"Time-to-Market\" for new features."
            },
            {
              "type": "image",
              "src": "product-why-does-a-design-system-matter-7.jpg",
              "caption": ""
            },
            {
              "type": "image",
              "src": "product-why-does-a-design-system-matter-8.jpg",
              "caption": ""
            },
            {
              "type": "image",
              "src": "product-why-does-a-design-system-matter-9.jpg",
              "caption": ""
            },
            {
              "type": "image",
              "src": "product-why-does-a-design-system-matter-10.jpg",
              "caption": ""
            }
          ],
          "quote": null
        },
        "project": "Ohyoung B2B & CRM Systems",
        "cover": "product-why-does-a-design-system-matter.jpg"
      },
      {
        "id": "ohyoung-b2b-crm",
        "title": "What Are the User Needs?",
        "project": "Ohyoung B2B & CRM Systems",
        "year": "2024–2025",
        "duo": [
          "#1E293B",
          "#4C6B8A"
        ],
        "tags": [
          "Business Strategy",
          "User Research",
          "User Flow",
          "0→1 Product"
        ],
        "summary": "I designed a 0-to-1 B2B CRM framework that transformed fragmented manual processes into a flexible, scalable workflow for multiple language schools.",
        "blog": {
          "intro": "In this 0-to-1 B2B CRM project, the main challenge was not simply improving an existing tool, but defining a new operational workflow from scratch. Internal teams were relying on fragmented manual processes that had never been formalized, while each language school had its own way of managing registration, scheduling, and student information. Through user interviews, observational research, and cross-functional workshops, I mapped these analog pain points and identified the need for a flexible standard: a centralized framework strong enough to maintain data consistency, but adaptable enough to support different school operations. This helped shift the project from basic digitization toward a scalable CRM ecosystem built around efficiency, role clarity, and long-term growth.",
          "sections": [
            {
              "h": "Building a B2B Ecosystem from 0 to 1",
              "p": "Creating a system from scratch is more than just digitizing paperwork; it's about defining a new way of working. In the early stages of this B2B CRM, the \"user need\" wasn't just a better tool — it was a coherent workflow where none existed."
            },
            {
              "h": "Defining the Problem: Architecting a New Reality",
              "p": "In a 0-1 project, the biggest challenge is the lack of a baseline. Internal users were struggling with fragmented, manual processes that had never been formalized. The goal wasn't just to fix a \"broken\" system, but to invent one.\n\n• The Mission: To design a centralized registration framework that replaced labor-intensive manual entries.\n• The Metric: We set a benchmark to improve operational efficiency by at least 10% from day one of the rollout."
            },
            {
              "type": "image",
              "src": "product-what-are-the-user-needs-3.jpg",
              "caption": ""
            },
            {
              "h": "User Research: Mapping the Unseen",
              "p": "When there is no existing system to audit, you have to observe the people. I conducted multiple rounds of interviews and observational studies across diverse language schools to understand their \"analog\" pain points.\n\n• The Strategic Discovery: I identified a critical tension — each school had its own unique \"operational DNA.\"\n• The Insight: To succeed at 0-1, the system couldn't be a \"one-size-fits-all\" cage. It needed to be a flexible standard: a core framework robust enough for data integrity, but modular enough to adapt to local school cultures."
            },
            {
              "h": "Ideation: Turning Chaos into Structure",
              "p": "With no legacy system to hold us back, the ideation phase was about structural innovation. I led workshops to brainstorm how we could eliminate redundant manual steps before they even reached the digital interface.\n\nOur focus shifted to three pillars of 0-1 design:\n• Zero Redundancy: Designing data entry points that follow a \"write once, use everywhere\" philosophy.\n• Role Clarity: Establishing clear digital ownership to replace the \"who-does-what\" confusion of manual workflows.\n• Future-Proofing: Creating a seamless user experience that could scale as the organization grew."
            },
            {
              "type": "image",
              "src": "product-what-are-the-user-needs-6.jpg",
              "caption": "Before"
            },
            {
              "type": "image",
              "src": "product-what-are-the-user-needs-7.jpg",
              "caption": "After"
            }
          ],
          "quote": null
        },
        "cover": "product-what-are-the-user-needs.jpg"
      }
    ],
    "ux": [
      {
        "id": "redefining-users-workflows",
        "title": "Redefining Users and Workflows",
        "project": "YesOnline E-Learning System",
        "year": "2023–2025",
        "duo": [
          "#4C6B8A",
          "#B8B4D8"
        ],
        "tags": [
          "User Flow",
          "User Research",
          "User Interviews"
        ],
        "summary": "I redefined the product’s user structure from two basic roles into a five-role ecosystem, transforming the platform from a simple E-learning tool into a hybrid E-learning and CRM system.",
        "blog": {
          "intro": "The legacy product had completed its first development phase, but users still struggled to use it in real academic workflows. Through stakeholder interviews, requirement grooming, and cross-functional discussions, I identified a major alignment gap: different departments had different understandings of who the product served and what it was meant to achieve. By mapping the actual needs of students, instructors, administrative staff, academic coordinators, and sales representatives, I redefined the system around five distinct user roles. This shifted the product direction from a basic class-booking platform into a more strategic hybrid system that connected E-learning operations with CRM-driven student support.",
          "sections": [
            {
              "h": "How many users are there, really?",
              "p": "The primary pain point of the legacy product was that, despite completing the first phase of development, users were still unable to use it \"normally.\" The workflows didn't align with their actual needs; specifically, the course selection logic was incompatible with existing academic processes, making it unusable for students.\n\nInitially, the team identified only two user roles: internal staff and students. The product was narrowly defined as a simple E-learning system where students booked classes and staff managed orders and schedules."
            },
            {
              "h": "User Research & Product Evolution",
              "p": "Through stakeholder interviews and requirement grooming with the marketing team, I discovered a significant \"alignment gap\" — every department had a different understanding of the product's core purpose.\n\nFollowing deep-dive research and cross-functional discussions, I redefined the system to support five distinct user roles for the Phase 1 launch. This shifted the product's identity from a basic E-learning tool to a sophisticated hybrid system combining E-learning and CRM (Customer Relationship Management)."
            },
            {
              "type": "image",
              "src": "ux-redefining-users-and-workflows-3.jpg",
              "caption": ""
            },
            {
              "h": "User Personas",
              "p": "External Users\n• Instructors: A diverse group of international teachers requiring multi-language support (English, Japanese, German, French, etc.). They rely on the system to prepare materials, track student progress, manage leave requests, and set their teaching availability.\n• Students: A broad demographic including university students, working professionals, and parents. Their goals are to schedule, skip, or cancel classes, track their learning history, and monitor their proficiency levels.\nInternal Staff\n• Administrative Staff: They act as a support bridge, assisting with manual course bookings and handling emergency leave for both teachers and students. They require tools for batch scheduling to maximize efficiency.\n• Academic Coordinators: Responsible for teacher management, focusing on reviewing and auditing instructor schedules and workloads.\n• Sales Representatives: Focused on student success and retention; they need access to their specific assigned students to monitor learning progress and provide personalized care."
            }
          ],
          "quote": null
        },
        "cover": "ux-redefining-users-and-workflows.jpg"
      },
      {
        "id": "bi-dashboard",
        "title": "Making Business Goals Visible Through Data",
        "project": "Internal Business Intelligence Dashboard",
        "year": "2025",
        "duo": [
          "#4C6B8A",
          "#6B7F6B"
        ],
        "tags": [
          "UX Strategy",
          "Data Visualization",
          "Internal Tools",
          "Design Leadership"
        ],
        "summary": "I led the UX strategy and design launch of an internal business intelligence dashboard, transforming fragmented operational data into a clear decision-making tool for internal teams.",
        "blog": {
          "intro": "This project was an internal monitoring system designed to help business teams understand performance, track key metrics, and make faster decisions through data visualization. Before the dashboard, important business information was scattered across different sources, making it difficult for teams to see the full picture or connect daily operations with larger business goals. As the Senior UX Designer and Design Lead, I was responsible for shaping the product structure, defining the dashboard logic, guiding the visual hierarchy, and leading the design toward launch. My focus was to turn complex data into an intuitive experience that helped users not only read numbers, but understand what required attention, comparison, or action.",
          "sections": [
            {
              "h": "Translating Business Goals into Dashboard Logic",
              "p": "The main UX challenge was not simply deciding how to display data, but determining what the data needed to communicate. I worked from the business goals backward, identifying which metrics mattered most, how different teams would interpret them, and what decisions the dashboard needed to support. This helped transform the product from a large data board into a structured monitoring experience, where users could quickly understand performance status, identify changes, and recognize which areas needed follow-up."
            },
            {
              "h": "Designing for Clarity, Priority, and Action",
              "p": "Because the dashboard contained a large amount of information, I focused on reducing cognitive load through clear information hierarchy, visual grouping, and progressive levels of detail. High-level indicators were designed for quick scanning, trend visualizations helped users identify changes over time, and detailed data sections supported deeper investigation when needed. The goal was to make the dashboard feel less like a data archive and more like a decision-support system that guided users from overview to insight."
            },
            {
              "type": "image",
              "src": "ux-making-business-goals-visible-through-da-3.jpg",
              "caption": ""
            },
            {
              "h": "Leading the Product Toward Launch",
              "p": "As the Design Lead, I guided the product from UX structure to final launch, ensuring that the dashboard remained consistent, scalable, and aligned with business priorities. My role included defining the user flow, shaping the visual language of the data views, reviewing design consistency, and supporting cross-functional communication during implementation. This project strengthened my ability to lead internal tool design at the intersection of business strategy, operational complexity, and data-driven decision-making."
            }
          ],
          "quote": null
        },
        "cover": "ux-making-business-goals-visible-through-da.jpg"
      },
      {
        "id": "ohyoung-b2b-crm",
        "title": "What Are the User Needs?",
        "project": "Ohyoung B2B & CRM Systems",
        "year": "2024–2025",
        "duo": [
          "#1E293B",
          "#4C6B8A"
        ],
        "tags": [
          "Business Strategy",
          "User Research",
          "User Flow",
          "0→1 Product"
        ],
        "summary": "I designed a 0-to-1 B2B CRM framework that transformed fragmented manual processes into a flexible, scalable workflow for multiple language schools.",
        "blog": {
          "intro": "In this 0-to-1 B2B CRM project, the main challenge was not simply improving an existing tool, but defining a new operational workflow from scratch. Internal teams were relying on fragmented manual processes that had never been formalized, while each language school had its own way of managing registration, scheduling, and student information. Through user interviews, observational research, and cross-functional workshops, I mapped these analog pain points and identified the need for a flexible standard: a centralized framework strong enough to maintain data consistency, but adaptable enough to support different school operations. This helped shift the project from basic digitization toward a scalable CRM ecosystem built around efficiency, role clarity, and long-term growth.",
          "sections": [
            {
              "h": "Building a B2B Ecosystem from 0 to 1",
              "p": "Creating a system from scratch is more than just digitizing paperwork; it's about defining a new way of working. In the early stages of this B2B CRM, the \"user need\" wasn't just a better tool — it was a coherent workflow where none existed."
            },
            {
              "h": "Defining the Problem: Architecting a New Reality",
              "p": "In a 0-1 project, the biggest challenge is the lack of a baseline. Internal users were struggling with fragmented, manual processes that had never been formalized. The goal wasn't just to fix a \"broken\" system, but to invent one.\n\n• The Mission: To design a centralized registration framework that replaced labor-intensive manual entries.\n• The Metric: We set a benchmark to improve operational efficiency by at least 10% from day one of the rollout."
            },
            {
              "type": "image",
              "src": "ux-what-are-the-user-needs-3.jpg",
              "caption": ""
            },
            {
              "h": "User Research: Mapping the Unseen",
              "p": "When there is no existing system to audit, you have to observe the people. I conducted multiple rounds of interviews and observational studies across diverse language schools to understand their \"analog\" pain points.\n\n• The Strategic Discovery: I identified a critical tension — each school had its own unique \"operational DNA.\"\n• The Insight: To succeed at 0-1, the system couldn't be a \"one-size-fits-all\" cage. It needed to be a flexible standard: a core framework robust enough for data integrity, but modular enough to adapt to local school cultures."
            },
            {
              "h": "Ideation: Turning Chaos into Structure",
              "p": "With no legacy system to hold us back, the ideation phase was about structural innovation. I led workshops to brainstorm how we could eliminate redundant manual steps before they even reached the digital interface.\n\nOur focus shifted to three pillars of 0-1 design:\n• Zero Redundancy: Designing data entry points that follow a \"write once, use everywhere\" philosophy.\n• Role Clarity: Establishing clear digital ownership to replace the \"who-does-what\" confusion of manual workflows.\n• Future-Proofing: Creating a seamless user experience that could scale as the organization grew."
            },
            {
              "type": "image",
              "src": "ux-what-are-the-user-needs-6.jpg",
              "caption": "Before"
            },
            {
              "type": "image",
              "src": "ux-what-are-the-user-needs-7.jpg",
              "caption": "After"
            }
          ],
          "quote": null
        },
        "cover": "ux-what-are-the-user-needs.jpg"
      }
    ],
    "ai": [
      {
        "id": "workshop-management-system",
        "title": "My first AI Project, manage my own business",
        "project": "Workshop Management System",
        "year": "2025",
        "duo": [
          "#0F172A",
          "#B8B4D8"
        ],
        "tags": [
          "AI-build",
          "ERP",
          "Management System"
        ],
        "summary": "A workshop management tool designed for Cord n Yarn to centralize craft workshop planning, client records, budgets, templates, and client communication.",
        "link": "https://ningweiyun-hub.github.io/workshop-manager/workshop-manager.html",
        "linkNote": "Password: linen-clay-spool-amber-94",
        "blog": {
          "intro": "Workshop Manager is a self-initiated internal tool I built for Cord n Yarn, my craft workshop brand, to support the operational side of running small creative workshops. Instead of managing workshop details across scattered notes, spreadsheets, and repeated messages, the tool brings key workflows into one place: upcoming sessions, preparation tasks, client records, budgets, reusable material lists, and email templates. The goal was to turn a small handmade business workflow into a clearer, more scalable system, reducing manual effort while keeping the process personal and flexible.",
          "sections": [
            {
              "h": "From Handmade Workshops to Operational Systems",
              "p": "As the number of workshop ideas, participants, materials, and preparation tasks grew, I noticed that the challenge was no longer just designing the workshop experience itself. It was also about managing the behind-the-scenes operations: who joined which session, what materials were needed, what tasks were still pending, and how to communicate with clients consistently. This project started from that practical need: to create a lightweight system that could support creative work without making the process feel overcomplicated."
            },
            {
              "h": "Designing Around Real Small-Business Workflows",
              "p": "The system is structured around the core workflows of running craft workshops. The dashboard gives a quick overview of upcoming workshops and preparation tasks. The workshop section helps plan and track each session, while the client section keeps participant information organized. Budget tracking supports income and expense management, and reusable templates help reduce repetitive setup work for materials, checklists, and client emails. Rather than building isolated features, I designed the tool as a connected workflow that reflects how a small workshop business actually operates."
            },
            {
              "h": "Outcome and Next Steps",
              "p": "The current version transforms a personal operational pain point into a functional management system for workshop planning. It helps reduce scattered information, repeated manual work, and the mental load of preparing each session from scratch. For the next stage, I would like to improve automation around task reminders, client follow-ups, and budget summaries, while exploring how AI could help generate workshop checklists, material plans, and personalized email drafts based on each session type."
            }
          ],
          "quote": null
        },
        "cover": "ai-my-first-ai-project-manage-my-own-busine.jpg"
      },
      {
        "id": "food-spinner",
        "title": "Random idea from life",
        "project": "Food Spinner",
        "year": "2026",
        "duo": [
          "#B8B4D8",
          "#E07A5F"
        ],
        "tags": [
          "AI-build",
          "Management system",
          "Fun idea"
        ],
        "summary": "A personal food decision tool that combines a meal spinner, pantry tracking, and recipe management to reduce food waste and everyday meal-planning friction.",
        "link": "https://ningweiyun-hub.github.io/ns-food-spinner/",
        "blog": {
          "intro": "Meal Spinner started as a personal tool to solve two everyday problems: spending too much time deciding what to eat, and accidentally wasting food I had forgotten in the fridge or cupboard. By combining random meal generation with pantry and recipe management, the project explores how a playful interaction can support more practical food planning habits.",
          "sections": [
            {
              "h": "Why I made this?",
              "p": "I built Meal Spinner to solve a small but recurring problem in my daily life: I often spent too much time thinking about what to eat, while also forgetting ingredients I already had at home. This led to unnecessary food waste and decision fatigue around simple everyday meals.\n\nInstead of creating another static meal planner, I wanted to design something lighter and more playful. The idea was to turn meal planning into a quick interaction: set a meal preference, spin for an idea, then connect that decision back to what is actually available in the fridge or cupboard."
            },
            {
              "h": "From fun story to user needs",
              "p": "The project started from a fun personal observation: sometimes the hardest part of cooking is not the cooking itself, but deciding what to make. Behind that small moment, I identified a more practical user need: people need a simple way to connect food inspiration with household inventory.\n\nThat insight shaped the product into three connected parts: a meal spinner for quick decision-making, a pantry tracker for managing fridge and cupboard items, and a recipe collection for storing meal ideas. Together, these features help users move from \"What should I eat?\" to \"What can I make with what I already have?\""
            },
            {
              "h": "Outcome and next steps",
              "p": "The current prototype turns a personal pain point into a lightweight food management experience. It reduces the mental load of meal decisions while encouraging users to make better use of ingredients before they expire.\n\nFor the next stage, I would like to improve the connection between pantry items and recipe suggestions, so the spinner can prioritize meals based on available ingredients and expiry dates. I would also explore smarter reminders, ingredient matching, and more personalized meal logic to make the experience feel less random and more context-aware."
            }
          ],
          "quote": null
        },
        "cover": "ai-random-idea-from-life.jpg"
      },
      {
        "id": "small-talk-boxes",
        "title": "Make language practice easier.",
        "project": "Small Talk Boxes",
        "year": "2026",
        "duo": [
          "#4C6B8A",
          "#B8B4D8"
        ],
        "tags": [
          "Fun idea",
          "Learning Platform",
          "Mock Interview"
        ],
        "summary": "An English small talk practice tool that helps users build speaking confidence through themed prompts, timed responses, and low-pressure daily practice.",
        "link": "https://ningweiyun-hub.github.io/small-talk-practice/",
        "blog": {
          "intro": "English Small Talk Practice is a self-initiated learning tool designed to help users practise spontaneous English speaking in a simple and structured way. Instead of preparing perfect answers in advance, users can choose a theme, draw a random question, and speak within a timed session. The goal is to make speaking practice feel less intimidating by turning it into a repeatable, lightweight exercise that supports everyday conversation, interview preparation, and confidence building.",
          "sections": [
            {
              "h": "Turning Speaking Anxiety into a Small Daily Exercise",
              "p": "The project started from a common language-learning problem: many learners understand English, but struggle to respond naturally in real conversations. Small talk can feel especially difficult because it requires quick thinking, personal expression, and a sense of timing. I designed this tool to reduce that pressure by breaking speaking practice into small, manageable sessions where users only need to focus on one question at a time."
            },
            {
              "h": "Designing for Spontaneity and Structure",
              "p": "The experience is built around a simple interaction: pick a theme, draw a question, and speak for a set amount of time. The random prompt encourages spontaneous thinking, while the timer creates a clear practice boundary. This balance helps users practise speaking more naturally without feeling overwhelmed by an open-ended learning process."
            },
            {
              "h": "Outcome and Next Steps",
              "p": "The current version turns English speaking practice into a lightweight and repeatable web-based tool that users can use for daily warm-ups, small talk training, or interview preparation. The next step is to develop it into a mobile app, making the practice experience more accessible in everyday moments such as commuting, waiting between tasks, or preparing before conversations. I would also explore features such as answer history, self-reflection notes, difficulty levels, push reminders, and AI-generated feedback to help users build a more consistent speaking habit over time."
            }
          ],
          "quote": null
        },
        "cover": "ai-make-language-practice-easier.jpg"
      }
    ],
    "knit": [
      {
        "id": "crochet-bag-collection",
        "title": "Idea from My Daily Job",
        "year": "2026",
        "duo": [
          "#E07A5F",
          "#F2C48D"
        ],
        "tags": [
          "Crochet",
          "Bag Collection",
          "Spring Style",
          "Handmade Design"
        ],
        "summary": "A three-piece crochet bag collection developed through a design course, exploring how shared visual elements, material choices, and deadline constraints can shape a cohesive handmade series.",
        "blog": {
          "intro": "This project was the final outcome of a crochet design course, where the brief was to create a cohesive series of bags with at least two to three pieces connected by shared design elements. I designed a three-piece crochet bag collection, starting from sketches, material hunting, and timeline planning in late December. Although I originally planned to finish the project with \"perfect\" time management, the process quickly became a lesson in energy management, creative decision-making, and working within real constraints. In the end, the collection became more than a handmade assignment. It was a small but meaningful design project about structure, limitation, and knowing which ideas to keep when inspiration arrives at the last minute.",
          "sections": [
            {
              "h": "Designing a Collection, Not Just a Bag",
              "p": "The goal of this project was to create a series rather than a single object. Each bag needed to stand on its own while still feeling connected to the others through shared design elements. I explored form, proportion, texture, and material combinations to build a visual language that could carry across three pieces. This pushed me to think like a product designer as well as a maker: not only asking whether one piece looked good, but whether the full collection felt intentional and cohesive."
            },
            {
              "type": "image",
              "src": "knit-idea-from-my-daily-job-2.jpg",
              "caption": ""
            },
            {
              "h": "Time Management Became Energy Management",
              "p": "I planned the project timeline carefully, with enough milestones to keep myself moving toward the final deadline. Under ideal conditions, I should have finished by early March. In reality, the biggest constraint was not time, but energy. I realized that while I might technically have four to eight hours in a day, my truly focused creative hours were closer to two to four. This changed how I approached the work. Instead of forcing productivity through time blocks, I learned to design around the energy window where real making and decision-making could happen."
            },
            {
              "h": "Choosing What to Keep Under Pressure",
              "p": "In the final week before submission, new ideas started appearing quickly. I sketched several new directions, but crochet takes time, and not every idea could become a finished object. I had to make a clear design decision: narrow the concept down to what I could complete well, then strengthen the collection around those pieces. The final three-bag series was completed during a busy period of job searching, making the project feel like a deadline-fueled side quest. It reminded me that constraints do not always weaken creative work. Sometimes, they make the final direction sharper."
            }
          ],
          "quote": "We do not run on time. We run on energy."
        },
        "cover": "knit-idea-from-my-daily-job.jpg"
      },
      {
        "id": "handcraft-studio",
        "title": "Beyond the Laptop: My Handcraft Studio",
        "year": "2026",
        "duo": [
          "#F2C48D",
          "#6B7F6B"
        ],
        "tags": [
          "Handcraft",
          "Workshop"
        ],
        "summary": "A personal handcraft studio project where I bring knitting, crochet, macramé, and workshop experiences together beyond my digital design work.",
        "blog": {
          "intro": "Beyond the Laptop is a personal handcraft studio project that explores another side of my identity as a designer. While my professional work often happens through screens, systems, and digital products, handcraft allows me to reconnect with materials, process, and physical making. Through knitting, crochet, macramé, and small creative workshops, I use this studio as a space to experiment with texture, teach creative skills, and build meaningful experiences through hands-on practice.",
          "sections": [
            {
              "h": "Making as a Way of Thinking",
              "p": "Handcraft is not separate from my design practice. It is another way of solving problems, testing ideas, and understanding how people interact with materials. Through making, I pay attention to rhythm, structure, mistakes, repair, and patience. These details shape how I think as both a designer and a maker."
            },
            {
              "h": "Creating Workshops Around Slow Craft",
              "p": "The studio also extends into workshop experiences, where I design not only the final object but the learning journey itself. From preparing materials to breaking down techniques into beginner-friendly steps, each workshop is designed to help participants feel comfortable, creative, and supported. The goal is to make handcraft approachable, even for people who have never tried it before."
            },
            {
              "h": "A Personal Studio Beyond Digital Work",
              "p": "This project gives me a space to explore creativity beyond product design. It allows me to work with my hands, observe how people learn, and turn small creative practices into shared experiences. For me, the handcraft studio is not just a hobby, but an extension of my design identity: tactile, thoughtful, and deeply human."
            }
          ],
          "quote": "Beyond the laptop, design becomes something I can hold, teach, and share."
        },
        "cover": "knit-beyond-the-laptop-my-handcraft-studio.jpg"
      }
    ]
  },
  "blog": [
    {
      "id": "building-with-ai",
      "title": "Why I started building with AI",
      "year": "2026",
      "duo": [
        "#0F172A",
        "#B8B4D8"
      ],
      "tags": [
        "Side project",
        "Reflection"
      ],
      "summary": "A short note on how pairing with AI changed the kind of side projects I take on.",
      "published": false,
      "blog": {
        "intro": "This is your blog — a place for side projects, experiments, and notes that don't belong in a polished case study.\n\nWrite freely here. The same formatting as the case studies works: leave a blank line between paragraphs, and start a line with \"• \" to make a bullet.",
        "sections": [
          {
            "h": "A small experiment",
            "p": "Replace this with the story of something you made or learned recently — what you tried, what surprised you, what you'd do differently."
          }
        ],
        "quote": null
      }
    },
    {
      "id": "notes-on-slow-craft",
      "title": "Notes on slow craft",
      "year": "2025",
      "duo": [
        "#E07A5F",
        "#F2C48D"
      ],
      "tags": [
        "Knitting",
        "Process"
      ],
      "summary": "An unpublished example — flip its publish toggle in the admin to show how visibility works.",
      "published": false,
      "blog": {
        "intro": "This second post is left unpublished on purpose, so you can see how the admin publish toggle hides a draft from visitors while keeping it editable.",
        "sections": [],
        "quote": null
      }
    }
  ]
};
